name: Build-Test

on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
          
      - name: Install Node Packages
        run: npm ci
        
      - name: Build Local
        run: npm run build

      - name: Spell Check
        run: |
        # make file runnable, might not be necessary
        chmod +x ./spell-check/spell-check.sh
        bash ./spell-check/spell-check.sh
