name: Build-Test

on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node Packages
        run: npm ci

      - name: Spell Check
        run: bash "${GITHUB_WORKSPACE}/spell-check/spell-check.sh"
        
      - name: Build Local
        run: npm run build
